export const podcasts = [
    {
        id: 8,
        category: 'podcast',
        title: 'The power of forking',
        subtitle: 'Aditi talks about Celestia, forking as an evolutionary force, moats in web3, and emergent order.',
        url: 'https://www.othersidepod.xyz/episode/38',
    },
    {
        id: 7,
        category: 'podcast',
        title: 'Nick while on building the first modular blockchain network',
        subtitle: 'Celestia implements a novel design to unlock key properties such as scalability and sovereignty.',
        url: 'https://open.spotify.com/episode/2VvcOyrm65vuuY3WTFlo4L?si=niMcdCwQRzCUgC8-QJektw&nd=1',
    },
    {
        id: 6,
        category: 'podcast',
        title: 'Is Celestia the monolithic chain killer? The future of modular blockchains - Nick white, COO of Celestia, Ep. 184',
        subtitle: 'After Layer 1s and 2s, a new primitive is capturing the attention of the crypto community: the modular blockchain.',
        url: 'https://podcasts.apple.com/us/podcast/is-celestia-the-monolithic-chain-killer-the/id1350649166?i=1000550438055',
    },
    {
        id: 5,
        category: 'podcast',
        title: 'Episode 208: Digging into Data Availability with Ismail Khoffi from Celestia',
        subtitle: 'Chat with Ismail Khoffi from Celestia about how and why they’re focusing on building a data availability-first L1 blockchain',
        url: 'https://zeroknowledge.fm/208-2/',
    },
    {
        id: 1,
        category: 'podcast',
        title: 'Epicenter Episode 359 : Celestia - The Layer-1 Data Availability and Consensus Solution',
        subtitle: 'Celestia is a scalable general-purpose data availability layer for decentralized apps and trust-minimized sidechains.',
        url: 'https://epicenter.tv/episodes/359/',
    },
    {
        id: 2,
        category: 'podcast',
        title: 'ZK Podcast Episode 151: John Adler on Optimistic vs ZK Rollup and the data availability problem',
        subtitle: 'In this episode, we chat with John Adler – co-founder of Lazy Ledger (now Celestia) and Fuel Labs.',
        url: 'https://www.zeroknowledge.fm/151',
    },
    {
        id: 3,
        category: 'podcast',
        title: 'The Blockchain Debate Podcast Episode 17 : ZK vs Optimistic Rollups',
        subtitle: 'Motion: ZK rollup has a better set of security/scalability tradeoff than optimistic rollup (Alex Gluchowski vs. John Adler, co-host: James Prestwich)',
        url: 'https://blockdebate.buzzsprout.com/767033/6210781',
    },
    {
        id: 4,
        category: 'podcast',
        title: 'Interchain.FM',
        subtitle: 'Celestia: Data Availability Layer for Easily Deploying Appchains in Cosmos',
        url: 'https://interchain.fm/episodes/celestia-data-availability-layer-for-easily-deploying-appchains-on-cosmos-8yOokETD',
    },
]
